CREATE USER 'admin'@'%' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON mydatabase.* TO 'admin'@'%';
FLUSH PRIVILEGES;

USE mydatabase;
CREATE TABLE User (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
);
